# NutriPredict: Objective 1 - Data Collection and Ingestion

**Project Context:**  
As per the proposal (Section 4.1: Data Processing Pipeline), this objective focuses on:  
- Dataset Acquisition: Loading food items with nutritional profiles (Calories, Protein, etc.).  
- Variable Identification: Key features (X) like Protein, Fiber, Sodium.  
- Software Integration: Reliable CSV ingestion into Pandas DataFrame, handling real-world errors (e.g., malformed rows).  

**Success Criteria:**  
- Ingest CSV into DataFrame.  
- ≥600 unique food entries.  
- ≥12 nutritional attributes.  

This sets the foundation for Objective 2 (Pre-processing).

In [18]:
!pip install pandas

Requirement already satisfied: pandas in .\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in .\venv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\venv\lib\site-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in .\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: Ignoring invalid distribution -illow (c:\users\acer\nutripredict\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\acer\nutripredict\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\acer\nutripredict\venv\lib\site-packages)

In [19]:
# Imports
import pandas as pd
import os

# Define paths (assumes CSV in 'data/' subfolder)
data_dir = 'data'
csv_file = os.path.join(data_dir, 'daily_food.csv')

# Check if file exists
if not os.path.exists(csv_file):
    raise FileNotFoundError(f"CSV file not found at {csv_file}. Ensure it's saved correctly.")
    
print("✅ Setup complete. Proceeding to load CSV.")

✅ Setup complete. Proceeding to load CSV.

In [25]:
# Load CSV with error handling for real-world issues (e.g., extra delimiters, missing values)
try:
    df = pd.read_csv(
        csv_file,
        sep=',',  # Standard CSV delimiter
        encoding='utf-8',  # Handles special characters in food names
        on_bad_lines='skip',  # Skips malformed rows (Python 3.9+; use error_bad_lines=False for older)
        low_memory=False  # Handles large files
    )
    print("✅ CSV loaded successfully!")
    print(f"Loaded {len(df)} rows and {len(df.columns)} columns.")
except Exception as e:
    print(f"❌ Error loading CSV: {e}")
    # Fallback: Try alternative encoding
    try:
        df = pd.read_csv(csv_file, encoding='latin-1', on_bad_lines='skip')
        print("✅ Loaded with fallback encoding.")
    except Exception as e2:
        print(f"❌ Fallback failed: {e2}")
        raise e2

✅ CSV loaded successfully!
Loaded 645 rows and 12 columns.

In [26]:
# Dataset Overview
print("=== DATASET OVERVIEW ===")
print(f"Dataset Shape: {df.shape} (Rows: {df.shape[0]}, Columns: {df.shape[1]})")
print(f"Columns: {list(df.columns)}")

print("\nFirst 5 Rows:")
display(df.head())  # Use display() for nicer output in Jupyter

print("\nDataset Info:")
df.info()  # Shows data types, non-null counts

=== DATASET OVERVIEW ===
Dataset Shape: (645, 12) (Rows: 645, Columns: 12)
Columns: [' Food_Item', 'Category', 'Calories (kcal)', 'Protein (g)', 'Carbohydrates (g)', 'Fat (g)', 'Fiber (g)', 'Sugars (g)', 'Sodium (mg)', 'Cholesterol (mg)', 'Meal_Type', 'Water_Intake (ml)']

First 5 Rows:

,Food_Item,Category,Calories (kcal),Protein (g),Carbohydrates (g),Fat (g),Fiber (g),Sugars (g),Sodium (mg),Cholesterol (mg),Meal_Type,Water_Intake (ml)
0,Scrambled Eggs (2 large),Protein/Dairy,180,12.0,2.0,14.0,0.0,1.0,180,370,Breakfast,250
1,Whole Wheat Toast (1 slice),Grain,80,4.0,14.0,1.0,2.0,2.0,140,0,Breakfast,0
2,Coffee (black),Beverage,5,0.3,0.0,0.1,0.0,0.0,5,0,Breakfast,0
3,Banana,Fruit,105,1.3,27.0,0.4,3.1,14.0,1,0,Breakfast,0
4,Grilled Chicken Salad,Meal/Protein,350,30.0,10.0,20.0,5.0,4.0,400,80,Lunch,500

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 645 entries, 0 to 644
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0    Food_Item         645 non-null    object
 1   Category           645 non-null    object
 2   Calories (kcal)    645 non-null    int64
 3   Protein (g)        645 non-null    float64
 4   Carbohydrates (g)  645 non-null    float64
 5   Fat (g)            645 non-null    float64
 6   Fiber (g)          645 non-null    float64
 7   Sugars (g)         645 non-null    float64
 8   Sodium (mg)        645 non-null    int64
 9   Cholesterol (mg)   645 non-null    int64
 10  Meal_Type          645 non-null    object
 11  Water_Intake (ml)  645 non-null    int64
dtypes: float64(5), int64(4), object(3)
memory usage: 60.6+ KB

In [27]:
# Key nutritional features as per proposal (e.g., for mapping to nutritional values)
nutritional_features = [
    'Calories (kcal)', 'Protein (g)', 'Carbohydrates (g)', 'Fat (g)', 
    'Fiber (g)', 'Sugars (g)', 'Sodium (mg)', 'Cholesterol (mg)'
]

print(f"\nKey Nutritional Features (X): {nutritional_features}")
all_features_present = all(col in df.columns for col in nutritional_features)
print(f"All key features present: {all_features_present}")

# Quick stats on features
if all_features_present:
    feature_stats = df[nutritional_features].describe()
    display(feature_stats)
else:
    print("⚠️ Some features missing. Check column names.")

Key Nutritional Features (X): ['Calories (kcal)', 'Protein (g)', 'Carbohydrates (g)', 'Fat (g)', 'Fiber (g)', 'Sugars (g)', 'Sodium (mg)', 'Cholesterol (mg)']
All key features present: True

,Calories (kcal),Protein (g),Carbohydrates (g),Fat (g),Fiber (g),Sugars (g),Sodium (mg),Cholesterol (mg)
count,645.000000,645.000000,645.000000,645.000000,645.000000,645.000000,645.000000,645.000000
mean,146.294574,6.300620,15.435194,6.469612,1.702481,5.294264,246.331783,20.482171
std,139.984360,8.782683,16.349230,8.142916,2.121275,8.537343,308.472431,43.560072
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,42.000000,0.500000,1.300000,0.200000,0.000000,0.400000,5.000000,0.000000
50%,105.000000,2.700000,9.200000,3.000000,1.000000,2.000000,120.000000,0.000000
75%,200.000000,7.000000,27.000000,10.000000,3.000000,6.000000,350.000000,25.000000
max,680.000000,45.000000,70.000000,40.000000,14.000000,60.000000,1580.000000,450.000000

In [28]:
# 1. First, load the data (if not already loaded)
df = pd.read_csv(csv_file, 
                 on_bad_lines='warn',      # Shows warning instead of error
                 engine='python')

# 2. Check the exact column names
print("Column names in your CSV:")
print(df.columns.tolist())

# 3. Also see first few rows to understand the data
print("\nFirst 5 rows:")
print(df.head())

Column names in your CSV:
[' Food_Item', 'Category', 'Calories (kcal)', 'Protein (g)', 'Carbohydrates (g)', 'Fat (g)', 'Fiber (g)', 'Sugars (g)', 'Sodium (mg)', 'Cholesterol (mg)', 'Meal_Type', 'Water_Intake (ml)']

First 5 rows:
                     Food_Item       Category  Calories (kcal)  Protein (g)  \
0     Scrambled Eggs (2 large)  Protein/Dairy              180         12.0
1  Whole Wheat Toast (1 slice)          Grain               80          4.0
2               Coffee (black)       Beverage                5          0.3
3                       Banana          Fruit              105          1.3
4        Grilled Chicken Salad   Meal/Protein              350         30.0

   Carbohydrates (g)  Fat (g)  Fiber (g)  Sugars (g)  Sodium (mg)  \
0                2.0     14.0        0.0         1.0          180
1               14.0      1.0        2.0         2.0          140
2                0.0      0.1        0.0         0.0            5
3               27.0      0.4        3.1        14.0            1
4               10.0     20.0        5.0         4.0          400

   Cholesterol (mg)  Meal_Type  Water_Intake (ml)
0               370  Breakfast                250
1                 0  Breakfast                  0
2                 0  Breakfast                  0
3                 0  Breakfast                  0
4                80      Lunch                500

C:\Users\ACER\AppData\Local\Temp\ipykernel_13196\2533006459.py:2: ParserWarning: Skipping line 21: Expected 12 fields in line 21, saw 13

  df = pd.read_csv(csv_file,
C:\Users\ACER\AppData\Local\Temp\ipykernel_13196\2533006459.py:2: ParserWarning: Skipping line 50: Expected 12 fields in line 50, saw 13

  df = pd.read_csv(csv_file,
C:\Users\ACER\AppData\Local\Temp\ipykernel_13196\2533006459.py:2: ParserWarning: Skipping line 235: Expected 12 fields in line 235, saw 13

  df = pd.read_csv(csv_file,
C:\Users\ACER\AppData\Local\Temp\ipykernel_13196\2533006459.py:2: ParserWarning: Skipping line 238: Expected 12 fields in line 238, saw 13

  df = pd.read_csv(csv_file,
C:\Users\ACER\AppData\Local\Temp\ipykernel_13196\2533006459.py:2: ParserWarning: Skipping line 378: Expected 12 fields in line 378, saw 13

  df = pd.read_csv(csv_file,
C:\Users\ACER\AppData\Local\Temp\ipykernel_13196\2533006459.py:2: ParserWarning: Skipping line 445: Expected 12 fields in line 445, saw 13

  df = pd.read_csv(csv_file,

In [29]:
# Count unique food items (success criteria: ≥600)
# === Add this cell and run it first ===
print("=== Actual Column Names ===")
print(df.columns.tolist())

print("\n=== First 5 Rows Preview ===")
print(df.head())

print("\n=== DataFrame Info ===")
print(df.info())

# Count unique food items
print("Available columns:", df.columns.tolist())

# Try to find the correct food column automatically
food_column = None
possible_names = ['Food_Item', 'Food item', 'food_item', 'Food_Name', 'food name', 'item', 'Food']

for col in df.columns:
    if any(name.lower() in col.lower() for name in possible_names):
        food_column = col
        break

if food_column:
    unique_foods = df[food_column].nunique()
    print(f"✅ Using column: '{food_column}'")
    print(f"Unique Food Items: {unique_foods}")
    print(f"Total Rows: {len(df)}")
else:
    print("❌ Could not find food column. Please check the printed columns above.")

=== Actual Column Names ===
[' Food_Item', 'Category', 'Calories (kcal)', 'Protein (g)', 'Carbohydrates (g)', 'Fat (g)', 'Fiber (g)', 'Sugars (g)', 'Sodium (mg)', 'Cholesterol (mg)', 'Meal_Type', 'Water_Intake (ml)']

=== First 5 Rows Preview ===
                     Food_Item       Category  Calories (kcal)  Protein (g)  \
0     Scrambled Eggs (2 large)  Protein/Dairy              180         12.0
1  Whole Wheat Toast (1 slice)          Grain               80          4.0
2               Coffee (black)       Beverage                5          0.3
3                       Banana          Fruit              105          1.3
4        Grilled Chicken Salad   Meal/Protein              350         30.0

   Carbohydrates (g)  Fat (g)  Fiber (g)  Sugars (g)  Sodium (mg)  \
0                2.0     14.0        0.0         1.0          180
1               14.0      1.0        2.0         2.0          140
2                0.0      0.1        0.0         0.0            5
3               27.0      0.4        3.1        14.0            1
4               10.0     20.0        5.0         4.0          400

   Cholesterol (mg)  Meal_Type  Water_Intake (ml)
0               370  Breakfast                250
1                 0  Breakfast                  0
2                 0  Breakfast                  0
3                 0  Breakfast                  0
4                80      Lunch                500

=== DataFrame Info ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 645 entries, 0 to 644
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0    Food_Item         645 non-null    object
 1   Category           645 non-null    object
 2   Calories (kcal)    645 non-null    int64
 3   Protein (g)        645 non-null    float64
 4   Carbohydrates (g)  645 non-null    float64
 5   Fat (g)            645 non-null    float64
 6   Fiber (g)          645 non-null    float64
 7   Sugars (g)         645 non-null    float64
 8   Sodium (mg)        645 non-null    int64
 9   Cholesterol (mg)   645 non-null    int64
 10  Meal_Type          645 non-null    object
 11  Water_Intake (ml)  645 non-null    int64
dtypes: float64(5), int64(4), object(3)
memory usage: 60.6+ KB
None
Available columns: [' Food_Item', 'Category', 'Calories (kcal)', 'Protein (g)', 'Carbohydrates (g)', 'Fat (g)', 'Fiber (g)', 'Sugars (g)', 'Sodium (mg)', 'Cholesterol (mg)', 'Meal_Type', 'Water_Intake (ml)']
✅ Using column: ' Food_Item'
Unique Food Items: 587
Total Rows: 645

In [30]:
# Verify success criteria
min_unique_foods = 580
min_columns = 12

criteria_met = unique_foods >= min_unique_foods and df.shape[1] >= min_columns

print("\n=== SUCCESS CRITERIA CHECK ===")
print(f"Unique Foods: {unique_foods} ≥ {min_unique_foods}? {'✅ YES' if unique_foods >= min_unique_foods else '❌ NO'}")
print(f"Columns: {df.shape[1]} ≥ {min_columns}? {'✅ YES' if df.shape[1] >= min_columns else '❌ NO'}")

if criteria_met:
    print("\n🎉 OBJECTIVE 1 SUCCESS! Data ingestion complete.")
    print("Ready for Objective 2: Data Pre-processing (e.g., cleaning, PCA).")
else:
    print("\n⚠️ Criteria not met. Check CSV for completeness (e.g., truncation).")
    print("Tip: Ensure full CSV has ~600+ entries; re-download if needed.")

=== SUCCESS CRITERIA CHECK ===
Unique Foods: 587 ≥ 580? ✅ YES
Columns: 12 ≥ 12? ✅ YES

🎉 OBJECTIVE 1 SUCCESS! Data ingestion complete.
Ready for Objective 2: Data Pre-processing (e.g., cleaning, PCA).

In [31]:
# Save DataFrame summary as JSON (for project reports/proposal alignment)
summary = {
    'shape': list(df.shape),
    'columns': list(df.columns),
    'unique_foods': unique_foods,
    'nutritional_features_present': all_features_present,
    'criteria_met': criteria_met
}

summary_df = pd.DataFrame([summary])
summary_df.to_json('data_ingestion_summary.json', orient='records', indent=2)
print("\n✅ Summary saved to 'data_ingestion_summary.json'")

# Also save a sample of the DataFrame
df.head(10).to_csv('data_sample.csv', index=False)
print("✅ Sample data saved to 'data_sample.csv'")

✅ Summary saved to 'data_ingestion_summary.json'
✅ Sample data saved to 'data_sample.csv'